In [1]:
from cctbx import sgtbx
#sg = sgtbx.space_group_info("19").group()

In [1]:
# new version uising eval - replace old version

##### ## test script below with full set of data
### apply reflection condition tests
### all_spacegroups: refactor for obe core per site - then can use 100s of cores
###     calculatte completion (no. of sites out of 1020?) and write to file.

# for each group/site check International tables and look at complementary conditions

import pickle
   
    
#filename = '0fbb95f5-17fe-4770-8b4c-417dbed90249' # test
filename = '775af26c-38bd-4138-8e4b-867a1dcda47a' # full model hkl to 5
with open(filename,"rb") as f0:
    (reflist, out) = pickle.load(f0)
  

# get statistics for calculation
sg_count, site_count, ref_count = 0, 0, 0
for sg in out:
    if sg[1] != {}:
        sg_count += 1
        for site in sg[1].keys():
            site_count += 1
            #ref_count += len(sg[1][site].keys())
            ref_count += len(sg[1][site]['ref'].keys())
print('\nCalculated:\n\tgroups:\t\t%s\n\tsites:\t\t%s\n\treflections:\t%s\n' % (sg_count, site_count, ref_count))
    
   
def even(num):
    return num/2 == num//2
    
def odd(num):
    return num/2 != num//2
      

   
myreflist = [[0,0,0], [2,0,0], [0,0,3], [4,2,0]]  # list of refs for class of tensor scattering

condDict = {}

# from international tables:
# condDict['#142_1'] = {'condExpr': 'even(h+k+l) and (l== 0 and (odd(h) or odd(k)) )' ,'condTex': 'stuff1...'}
# condDict['#142_2'] = {'condExpr': 'even(h+k+l) and (h== 0 and (odd(k) or odd(l)) )' ,'condTex': 'stuff2...'}
# condDict['#142_3'] = {'condExpr': 'even(h+k+l) and (h== k and not(2*h+l)%4 == 0)' ,'condTex': 'stuff3...'}
# condDict['#142_4'] = {'condExpr': 'even(h+k+l) and ((h==0 and k==0) and not(l%4==0))' ,'condTex': 'stuff4...'}
# condDict['#142_5'] = {'condExpr': 'even(h+k+l) and (k==0 and l==0) and odd(h)' ,'condTex': 'stuff5...'}
# condDict['#142_6'] = {'condExpr': 'even(h+k+l) and (h+k==0 and odd(h))' ,'condTex': 'stuff6...'}



# Dave Allan's typing of Jeremy Cockroft's tables
# hkl:         h + k + l =2n
# 0kl:         k,l = 2n
# h0l:        h,l = 2n
# hk0:       h,k = 2n
# hhl:        2h + l = 4n
# h00:       h = 2n
# 0k0:       k = 2n
# 00l:         l = 4n
# hh0:       h = 2n

# # from http://img.chem.ucl.ac.uk/sgp/large/142az2.htm
# condDict['#142_1'] = {'condExpr': 'even(h+k+l) and (h== 0 and (odd(k) or odd(l)) )' ,'condTex': 'stuff2...'}
# condDict['#142_2'] = {'condExpr': 'even(h+k+l) and (k== 0 and (odd(h) or odd(l)) )' ,'condTex': 'stuff2...'}
# condDict['#142_3'] = {'condExpr': 'even(h+k+l) and (l== 0 and (odd(h) or odd(k)) )' ,'condTex': 'stuff1...'}
# condDict['#142_4'] = {'condExpr': 'even(h+k+l) and (h== k and not(2*h+l)%4 == 0)' ,'condTex': 'stuff3...'}
# condDict['#142_5'] = {'condExpr': 'even(h+k+l) and (k==0 and l==0) and odd(h)' ,'condTex': 'stuff5...'}
# condDict['#142_6'] = {'condExpr': 'even(h+k+l) and (h==0 and l==0) and odd(k)' ,'condTex': 'stuff5...'}
# condDict['#142_7'] = {'condExpr': 'even(h+k+l) and ((h==0 and k==0) and not(l%4==0))' ,'condTex': 'stuff4...'}
# condDict['#142_8'] = {'condExpr': 'even(h+k+l) and (h==k and l==0) and odd(h)' ,'condTex': 'stuff3...'}
# # add h-h rules as 'permutations' (not in original)
# condDict['#142_9'] = {'condExpr': 'even(h+k+l) and (h==-k and not(2*h+l)%4 == 0)' ,'condTex': 'stuff3...'}
# condDict['#142_10'] = {'condExpr': 'even(h+k+l) and (h==-k and l==0) and odd(h)' ,'condTex': 'stuff3...'}

# from international tables, adding permutations
condDict['#142_1'] = {'condExpr': 'even(h+k+l) and (l== 0 and (odd(h) or odd(k)) )' ,'condTex': 'stuff1...'}
#condDict['#142_2'] = {'condExpr': 'even(h+k+l) and (h== 0 or k==0 and (odd(h) or odd(k) or odd(l)) )' ,'condTex': 'stuff2...'} #modified for perm
condDict['#142_2'] = {'condExpr': 'even(h+k+l) and ((h== 0 or k==0) and (odd(h) or odd(k) or odd(l)) )' ,'condTex': 'stuff2...'} #modified for perm
#condDict['#142_3'] = {'condExpr': 'even(h+k+l) and (h==k or h==-k and not(2*h+l)%4 == 0)' ,'condTex': 'stuff3...'} #modified for perm
condDict['#142_3'] = {'condExpr': 'even(h+k+l) and ((h==k or h==-k) and not(2*h+l)%4 == 0)' ,'condTex': 'stuff3...'} #modified for perm
condDict['#142_4'] = {'condExpr': 'even(h+k+l) and ((h==0 and k==0) and not(l%4==0))' ,'condTex': 'stuff4...'}
condDict['#142_5'] = {'condExpr': 'even(h+k+l) and ((h==0 or k==0) and l==0) and (odd(h) or odd(k))' ,'condTex': 'stuff5...'} #modified for perm
condDict['#142_6'] = {'condExpr': 'even(h+k+l) and ((h==k or h==-k) and odd(h))' ,'condTex': 'stuff6...'} #modified for perm



# create new rules from ANDing existing rules

def add_rules(dic):

    newrules = {}
    rules = list(condDict.keys())
    for r1 in rules:
        for r2 in rules:
            print('=== combining %s and %s' % (r1, r2))
            newrules[r1+r2] = {'condExpr': dic[r1]['condExpr'] + ' and ' +  dic[r2]['condExpr'],'condTex': 'stuff6...'}

    return newrules


newrules = add_rules(condDict)

# don't update: uncomment to add new rules
#condDict.update(newrules)


########################################################################
# reduce reflist to first sector - for test

reduce_str = 'k >= 0 and h >= k and l >= 0'

def reduce_refs(reflist, reduce_str):
    newreflist = []
    for ref in reflist:
        h, k, l = ref
        if eval(reduce_str):
            newreflist += [ref]
    return newreflist

reflist = reduce_refs(reflist, reduce_str)
###########################################################################


#add list of true reflections to each condition in codDict dictionary (might want to add false ones to help with logic??)
for cond in condDict.keys():
    condDict[cond]['condList'] = []
    for ref in reflist:
        #if condDict[cond]['condFunc'](ref):
        h, k, l = ref
        if eval(condDict[cond]['condExpr']):
            condDict[cond]['condList'] += [tuple(ref)]
    
    


def get_cond(refs):
    #find key in condDict that matches reflections in refs (or return None if none found)
    condkey = None
    for cond in condDict.keys():
        if set(condDict[cond]['condList']) == set(refs):
            condkey = cond
            break
    return(condkey)
        

#get_cond(myrefs)

 

# for each sg/site, create a disctionary of classes of tensors    
for sg in out:
    if sg[1] != {}:
        #print('#%i' % sg[0])
        for site in sg[1].keys():
            #print(site)
            #print(sg[1][site])
            
            sg[1][site]['classes'] = {}
            
            for ref in sg[1][site]['ref'].keys():
                #print(ref)
                ranks = sg[1][site]['ref'][ref]['ranks']
                #print(ranks)
    
                # is ref in existing class or need a new class?
                new_class = True
                for cls in sg[1][site]['classes']:
                    #if ranks in sg[1][site]['classes'][cls]['ranks']:
                    if ranks == sg[1][site]['classes'][cls]['ranks']:
                        sg[1][site]['classes'][cls]['refs'] += [ref]
                        new_class  = False
                    #else:
                    #    break
                
                if new_class:
                    if not bool(sg[1][site]['classes']): # empty dict
                        class_no = 1
                    else:
                        class_no = max(sg[1][site]['classes'].keys()) + 1 
                        
                    sg[1][site]['classes'][class_no] = {'refs': [ref], 'ranks': ranks}
                    
                        
#display all groups, sites & classes and 
for sg in out:
    if sg[1] != {}:
        for site in sg[1].keys():
            #print('sg: %i\tsite:%s' % (sg[0], site))
            #print(sg[1][site]['classes'])
            for cls in sg[1][site]['classes'].keys():
                print('sg: %i\t\tsite: %s\t\tclass: %i' % (sg[0], site, cls))
                print(sg[1][site]['classes'][cls])
                ref_cond = get_cond(sg[1][site]['classes'][cls]['refs'])
                sg[1][site]['classes'][cls]['refcond'] = ref_cond
                print('Reflection condtion:', ref_cond, '\n')
                
                        
                        
                        
#sg[1]
#    site
#        'ref'
#            (1,0,0)
#                'ranks'
#            (1,1,0)
#                'ranks'
#        'classes'
#            1
#                'ranks'
#                'refs'
#                'refcond
#        
#        
#            
                   
    
    




Calculated:
	groups:		157
	sites:		1022
	reflections:	116878

=== combining #142_1 and #142_1
=== combining #142_1 and #142_2
=== combining #142_1 and #142_3
=== combining #142_1 and #142_4
=== combining #142_1 and #142_5
=== combining #142_1 and #142_6
=== combining #142_2 and #142_1
=== combining #142_2 and #142_2
=== combining #142_2 and #142_3
=== combining #142_2 and #142_4
=== combining #142_2 and #142_5
=== combining #142_2 and #142_6
=== combining #142_3 and #142_1
=== combining #142_3 and #142_2
=== combining #142_3 and #142_3
=== combining #142_3 and #142_4
=== combining #142_3 and #142_5
=== combining #142_3 and #142_6
=== combining #142_4 and #142_1
=== combining #142_4 and #142_2
=== combining #142_4 and #142_3
=== combining #142_4 and #142_4
=== combining #142_4 and #142_5
=== combining #142_4 and #142_6
=== combining #142_5 and #142_1
=== combining #142_5 and #142_2
=== combining #142_5 and #142_3
=== combining #142_5 and #142_4
=== combining #142_5 and #142_5
=== combi

Reflection condtion: None 

sg: 50		site: f		class: 1
{'refs': [(-1, 0, 0), (0, -1, 0), (0, 1, 0), (1, 0, 0), (-1, 0, -1), (-1, 0, 1), (0, -1, -1), (0, -1, 1), (0, 1, -1), (0, 1, 1), (1, 0, -1), (1, 0, 1), (-2, -1, 0), (-2, 1, 0), (-1, -2, 0), (-1, 0, -2), (-1, 0, 2), (-1, 2, 0), (0, -1, -2), (0, -1, 2), (0, 1, -2), (0, 1, 2), (1, -2, 0), (1, 0, -2), (1, 0, 2), (1, 2, 0), (2, -1, 0), (2, 1, 0), (-3, 0, 0), (0, -3, 0), (0, 3, 0), (3, 0, 0), (-3, 0, -1), (-3, 0, 1), (-1, 0, -3), (-1, 0, 3), (0, -3, -1), (0, -3, 1), (0, -1, -3), (0, -1, 3), (0, 1, -3), (0, 1, 3), (0, 3, -1), (0, 3, 1), (1, 0, -3), (1, 0, 3), (3, 0, -1), (3, 0, 1), (-3, -2, 0), (-3, 0, -2), (-3, 0, 2), (-3, 2, 0), (-2, -3, 0), (-2, 3, 0), (0, -3, -2), (0, -3, 2), (0, 3, -2), (0, 3, 2), (2, -3, 0), (2, 3, 0), (3, -2, 0), (3, 0, -2), (3, 0, 2), (3, 2, 0), (-4, -1, 0), (-4, 1, 0), (-1, -4, 0), (-1, 0, -4), (-1, 0, 4), (-1, 4, 0), (0, -1, -4), (0, -1, 4), (0, 1, -4), (0, 1, 4), (1, -4, 0), (1, 0, -4), (1, 0, 4), (1, 4, 0), (4,

{'refs': [(-1, 0, 0), (0, -1, 0), (0, 1, 0), (1, 0, 0), (-3, 0, 0), (0, -3, 0), (0, 3, 0), (3, 0, 0), (-5, 0, 0), (0, -5, 0), (0, 5, 0), (5, 0, 0)], 'ranks': [2, 3, 4, 5, 6, -1, -2, -3, -4, -5, -6]}
Reflection condtion: None 

sg: 127		site: k		class: 2
{'refs': [(-1, 0, -1), (-1, 0, 1), (0, -1, -1), (0, -1, 1), (0, 1, -1), (0, 1, 1), (1, 0, -1), (1, 0, 1), (-1, 0, -2), (-1, 0, 2), (0, -1, -2), (0, -1, 2), (0, 1, -2), (0, 1, 2), (1, 0, -2), (1, 0, 2), (-3, 0, -1), (-3, 0, 1), (-1, 0, -3), (-1, 0, 3), (0, -3, -1), (0, -3, 1), (0, -1, -3), (0, -1, 3), (0, 1, -3), (0, 1, 3), (0, 3, -1), (0, 3, 1), (1, 0, -3), (1, 0, 3), (3, 0, -1), (3, 0, 1), (-3, 0, -2), (-3, 0, 2), (0, -3, -2), (0, -3, 2), (0, 3, -2), (0, 3, 2), (3, 0, -2), (3, 0, 2), (-1, 0, -4), (-1, 0, 4), (0, -1, -4), (0, -1, 4), (0, 1, -4), (0, 1, 4), (1, 0, -4), (1, 0, 4), (-3, 0, -3), (-3, 0, 3), (0, -3, -3), (0, -3, 3), (0, 3, -3), (0, 3, 3), (3, 0, -3), (3, 0, 3), (-3, 0, -4), (-3, 0, 4), (0, -3, -4), (0, -3, 4), (0, 3, -4), (0

sg: 223		site: e		class: 1
{'refs': [(-1, 0, 0), (0, -1, 0), (0, 0, -1), (0, 0, 1), (0, 1, 0), (1, 0, 0), (-3, 0, 0), (-2, -2, -1), (-2, -2, 1), (-2, -1, -2), (-2, -1, 2), (-2, 1, -2), (-2, 1, 2), (-2, 2, -1), (-2, 2, 1), (-1, -2, -2), (-1, -2, 2), (-1, 2, -2), (-1, 2, 2), (0, -3, 0), (0, 0, -3), (0, 0, 3), (0, 3, 0), (1, -2, -2), (1, -2, 2), (1, 2, -2), (1, 2, 2), (2, -2, -1), (2, -2, 1), (2, -1, -2), (2, -1, 2), (2, 1, -2), (2, 1, 2), (2, 2, -1), (2, 2, 1), (3, 0, 0), (-3, -2, -2), (-3, -2, 2), (-3, 2, -2), (-3, 2, 2), (-2, -3, -2), (-2, -3, 2), (-2, -2, -3), (-2, -2, 3), (-2, 2, -3), (-2, 2, 3), (-2, 3, -2), (-2, 3, 2), (2, -3, -2), (2, -3, 2), (2, -2, -3), (2, -2, 3), (2, 2, -3), (2, 2, 3), (2, 3, -2), (2, 3, 2), (3, -2, -2), (3, -2, 2), (3, 2, -2), (3, 2, 2), (-5, 0, 0), (0, -5, 0), (0, 0, -5), (0, 0, 5), (0, 5, 0), (5, 0, 0), (-5, -2, -2), (-5, -2, 2), (-5, 2, -2), (-5, 2, 2), (-4, -4, -1), (-4, -4, 1), (-4, -1, -4), (-4, -1, 4), (-4, 1, -4), (-4, 1, 4), (-4, 4, -1), (-4, 4, 1), 

In [2]:
################
#
# look at class 2: reflections that do not satisfy any rules! check rules
#
################


sg = out[141] # #154
site = 'g'

for cls in sg[1][site]['classes'].keys():
    print('sg: %i\t\tsite: %s\t\tclass: %i' % (sg[0], site, cls))
    print(sg[1][site]['classes'][cls])
    ref_cond = get_cond(sg[1][site]['classes'][cls]['refs'])
    sg[1][site]['classes'][cls]['refcond'] = ref_cond
    print('Reflection condtion:', ref_cond, '\n')
    
    for ref in sg[1][site]['classes'][cls]['refs']:
        h, k, l = ref
        if eval(reduce_str):### aply only to reduces ref list
            allowed = ''
            for cond in condDict.keys():
                if eval(condDict[cond]['condExpr']):
                    allowed += 'T  '
                else:
                    allowed += '.  '          
            print('%3i %3i %3i %s' % (h, k, l, allowed))
                

sg: 142		site: g		class: 1
{'refs': [(-1, -1, 0), (-1, 1, 0), (1, -1, 0), (1, 1, 0), (-3, -3, 0), (-3, 3, 0), (3, -3, 0), (3, 3, 0), (-5, -5, 0), (-5, 5, 0), (5, -5, 0), (5, 5, 0)], 'ranks': [1, 2, 3, 4, 5, 6, -2, -3, -4, -5, -6], 'refcond': None}
Reflection condtion: None 

  1   1   0 T  .  T  .  .  T  
  3   3   0 T  .  T  .  .  T  
  5   5   0 T  .  T  .  .  T  
sg: 142		site: g		class: 2
{'refs': [(-1, 0, -1), (-1, 0, 1), (0, -1, -1), (0, -1, 1), (0, 1, -1), (0, 1, 1), (1, 0, -1), (1, 0, 1), (-3, -1, 0), (-3, 0, -1), (-3, 0, 1), (-3, 1, 0), (-1, -3, 0), (-1, 0, -3), (-1, 0, 3), (-1, 3, 0), (0, -3, -1), (0, -3, 1), (0, -1, -3), (0, -1, 3), (0, 1, -3), (0, 1, 3), (0, 3, -1), (0, 3, 1), (1, -3, 0), (1, 0, -3), (1, 0, 3), (1, 3, 0), (3, -1, 0), (3, 0, -1), (3, 0, 1), (3, 1, 0), (-2, -2, -2), (-2, -2, 2), (-2, 2, -2), (-2, 2, 2), (2, -2, -2), (2, -2, 2), (2, 2, -2), (2, 2, 2), (-3, 0, -3), (-3, 0, 3), (-1, -1, -4), (-1, -1, 4), (-1, 1, -4), (-1, 1, 4), (0, -3, -3), (0, -3, 3), (0, 3, -

In [13]:
# there are no reflections that satisfy any of these sets of truth tables (with the last being OR of four)
# These ARE the rules - just need simplifying!

######## to here Tuesday 11th April ###############################

tt = [[True, False, True, False, False, True]]
tt = [[False, False, True, True, False, False]]
tt = [[True, False, False, False, False, False], 
      [False, True, False, False, False, False],
      [False, False, True, False, False, False],
      [False, False, True, False, False, True]
     ]

for ref in reflist:
    tt_ref = []   # truth table for ref
    for cond in condDict.keys():
        h, k, l = ref
        tt_ref += [eval(condDict[cond]['condExpr'])] # create truth table for reflection
        
    if tt_ref in tt:
        print(ref, tt_ref)
           



[1 0 1] [False, True, False, False, False, False]
[1 0 3] [False, True, False, False, False, False]
[3 0 1] [False, True, False, False, False, False]
[3 1 0] [True, False, False, False, False, False]
[2 2 2] [False, False, True, False, False, False]
[1 1 4] [False, False, True, False, False, True]
[3 0 3] [False, True, False, False, False, False]
[1 0 5] [False, True, False, False, False, False]
[5 0 1] [False, True, False, False, False, False]
[5 1 0] [True, False, False, False, False, False]
[3 0 5] [False, True, False, False, False, False]
[3 3 4] [False, False, True, False, False, True]
[5 0 3] [False, True, False, False, False, False]
[5 3 0] [True, False, False, False, False, False]
[4 4 2] [False, False, True, False, False, False]
[5 0 5] [False, True, False, False, False, False]
[5 5 4] [False, False, True, False, False, True]


In [46]:
h, k, l = 0, 0, 2
cond = '#142_2'
print(cond, ': ', condDict[cond]['condExpr'])
eval(condDict[cond]['condExpr'])

#142_2 :  even(h+k+l) and (h== 0 or k==0 and (odd(h) or odd(k) or odd(l)) )


True

In [4]:
condDict['#142_3']['condList']

[(0, 0, 0),
 (-1, -1, 0),
 (-1, 1, 0),
 (1, -1, 0),
 (1, 1, 0),
 (0, 0, -2),
 (0, 0, 2),
 (-1, -1, -2),
 (-1, -1, 2),
 (1, 1, -2),
 (1, 1, 2),
 (-2, -2, 0),
 (2, 2, 0),
 (-2, -2, -2),
 (-2, -2, 2),
 (-2, 2, -2),
 (-2, 2, 2),
 (2, -2, -2),
 (2, -2, 2),
 (2, 2, -2),
 (2, 2, 2),
 (0, 0, -4),
 (0, 0, 4),
 (-3, -3, 0),
 (-3, 3, 0),
 (-1, -1, -4),
 (-1, -1, 4),
 (-1, 1, -4),
 (-1, 1, 4),
 (1, -1, -4),
 (1, -1, 4),
 (1, 1, -4),
 (1, 1, 4),
 (3, -3, 0),
 (3, 3, 0),
 (-3, -3, -2),
 (-3, -3, 2),
 (3, 3, -2),
 (3, 3, 2),
 (-2, -2, -4),
 (-2, -2, 4),
 (2, 2, -4),
 (2, 2, 4),
 (-4, -4, 0),
 (4, 4, 0),
 (-3, -3, -4),
 (-3, -3, 4),
 (-3, 3, -4),
 (-3, 3, 4),
 (3, -3, -4),
 (3, -3, 4),
 (3, 3, -4),
 (3, 3, 4),
 (-4, -4, -2),
 (-4, -4, 2),
 (-4, 4, -2),
 (-4, 4, 2),
 (4, -4, -2),
 (4, -4, 2),
 (4, 4, -2),
 (4, 4, 2),
 (-4, -4, -4),
 (-4, -4, 4),
 (4, 4, -4),
 (4, 4, 4),
 (-5, -5, 0),
 (-5, 5, 0),
 (5, -5, 0),
 (5, 5, 0),
 (-5, -5, -2),
 (-5, -5, 2),
 (5, 5, -2),
 (5, 5, 2),
 (-5, -5, -4),
 (-5, -5, 4),

In [5]:
import TensorScatteringClass as ten
import numpy as np

t=ten.TensorScatteringClass(spacegroup_number = 142, wyckoff_letter = 'g')

t.hkl = np.array([1, 1, 0])

#print(t.SF_symmetry(t.sitevec, t.hkl, t.sglist))

t.TensorCalc(hkl = t.hkl, K=2, Parity=1, Time=1)

t.print_tensors()


Crystal properties

                    CIF file:  Spacegroup # 142
                     Lattice:  0.500 0.500 0.500 90.00 90.00 90.00
                   All sites:  
               Site selected:  32 g
                 Site vector:  0.088 0.702 0.358
       No. of spacegroup ops:  32
      No. of sym ops at site:  1
 No. of equiv. sites in cell:  32
   No. of pg ops for crystal:  16

Tensor properties

             Required parity:  Even
          Required time sym.:  Even
                         hkl:  [1.0, 1.0, 0.0]
                Site allowed:  No
   Structure factor for site:  -0.00+0.00i
          Spacegroup allowed:  No
              Tensor allowed:  Yes
                      Parity:  Either
                        Time:  Either
                          PT:  Either
              Glide or screw:  True

Tensor components

         Crystal (spherical):  [-0.+0.j -0.+0.j  1.+0.j  0.+0.j -0.-0.j]
            Atom (spherical):  [ 0.258-0.511j  1.   +0.j     0.002-0.849j  1.   +0.0

In [6]:
# 4/mmm, consider only h, k, l positive; h>=k
# 

#[ref in reflist if ref[0]>=0]
 
[ref for ref in reflist if ref[0]>=0 and ref[1]>=0 and ref[2]>=0 and ref[0]>=ref[1]]
 

[array([0, 0, 0]),
 array([0, 0, 1]),
 array([1, 0, 0]),
 array([1, 0, 1]),
 array([1, 1, 0]),
 array([1, 1, 1]),
 array([0, 0, 2]),
 array([2, 0, 0]),
 array([1, 0, 2]),
 array([2, 0, 1]),
 array([2, 1, 0]),
 array([1, 1, 2]),
 array([2, 1, 1]),
 array([2, 0, 2]),
 array([2, 2, 0]),
 array([0, 0, 3]),
 array([2, 1, 2]),
 array([2, 2, 1]),
 array([3, 0, 0]),
 array([1, 0, 3]),
 array([3, 0, 1]),
 array([3, 1, 0]),
 array([1, 1, 3]),
 array([3, 1, 1]),
 array([2, 2, 2]),
 array([2, 0, 3]),
 array([3, 0, 2]),
 array([3, 2, 0]),
 array([2, 1, 3]),
 array([3, 1, 2]),
 array([3, 2, 1]),
 array([0, 0, 4]),
 array([4, 0, 0]),
 array([1, 0, 4]),
 array([2, 2, 3]),
 array([3, 2, 2]),
 array([4, 0, 1]),
 array([4, 1, 0]),
 array([1, 1, 4]),
 array([3, 0, 3]),
 array([3, 3, 0]),
 array([4, 1, 1]),
 array([3, 1, 3]),
 array([3, 3, 1]),
 array([2, 0, 4]),
 array([4, 0, 2]),
 array([4, 2, 0]),
 array([2, 1, 4]),
 array([4, 1, 2]),
 array([4, 2, 1]),
 array([3, 2, 3]),
 array([3, 3, 2]),
 array([2, 2

In [7]:
ll = [1,2,3,4,5]
[l for l in ll]

[1, 2, 3, 4, 5]

In [8]:
#         sgi = sg.space_group_info(sg_num)
#         sg = sgi.group()
#         w = sgi.wyckoff_table()

In [19]:
import cctbx.sgtbx as sg
sgi = sg.space_group_info(142)
sg = sgi.group()
sgi.symbol_and_number() # 'I 41/a c d :2 (No. 142)'
sym_num_str = sgi.symbol_and_number()
print(sym_num_str[0])
print(sgi.show_summary())


I
Space group: I 41/a c d :2 (No. 142)
None


In [11]:
sgi.symbol_and_number()

'I 41/a c d :2 (No. 142)'

In [3]:
sg.all_ops()

(<cctbx_sgtbx_ext.rt_mx at 0x7f1f40177eb0>,
 <cctbx_sgtbx_ext.rt_mx at 0x7f1f28030230>)

In [4]:
sgi = sgtbx.space_group_info(142)
#     if (co.primitive):
#       sgi = sgi.primitive_setting()
sgi.show_summary()
gr = sgi.group()
print("  Crystal system:", gr.crystal_system())
print("  Point group type:", gr.point_group_type())
print("  Laue group type:", gr.laue_group_type())
print("  Number of symmetry operations:", gr.order_z())
print("  Lattice centering operations:", gr.n_ltr())

NameError: name 'sgtbx' is not defined

In [13]:
# apply these to h,k,l?
for op in gr.build_derived_laue_group().all_ops():
    print(op.as_xyz())

x,y,z
-y,x,z
-x,-y,z
y,-x,z
x,-y,-z
y,x,-z
-x,y,-z
-y,-x,-z
-x,-y,-z
y,-x,-z
x,y,-z
-y,x,-z
-x,y,z
-y,-x,z
x,-y,z
y,x,z


In [14]:
# all laue group ops - hex and rhomb havethings like x+y
for sgnum in range(1,230+1):
    sgi = sgtbx.space_group_info(sgnum)
    sgi.show_summary()
    gr = sgi.group()
    for op in gr.build_derived_laue_group().all_ops():
        print(op.as_xyz())

Space group: P 1 (No. 1)
x,y,z
-x,-y,-z
Space group: P -1 (No. 2)
x,y,z
-x,-y,-z
Space group: P 1 2 1 (No. 3)
x,y,z
-x,y,-z
-x,-y,-z
x,-y,z
Space group: P 1 21 1 (No. 4)
x,y,z
-x,y,-z
-x,-y,-z
x,-y,z
Space group: C 1 2 1 (No. 5)
x,y,z
-x,y,-z
-x,-y,-z
x,-y,z
Space group: P 1 m 1 (No. 6)
x,y,z
x,-y,z
-x,-y,-z
-x,y,-z
Space group: P 1 c 1 (No. 7)
x,y,z
x,-y,z
-x,-y,-z
-x,y,-z
Space group: C 1 m 1 (No. 8)
x,y,z
x,-y,z
-x,-y,-z
-x,y,-z
Space group: C 1 c 1 (No. 9)
x,y,z
x,-y,z
-x,-y,-z
-x,y,-z
Space group: P 1 2/m 1 (No. 10)
x,y,z
-x,y,-z
-x,-y,-z
x,-y,z
Space group: P 1 21/m 1 (No. 11)
x,y,z
-x,y,-z
-x,-y,-z
x,-y,z
Space group: C 1 2/m 1 (No. 12)
x,y,z
-x,y,-z
-x,-y,-z
x,-y,z
Space group: P 1 2/c 1 (No. 13)
x,y,z
-x,y,-z
-x,-y,-z
x,-y,z
Space group: P 1 21/c 1 (No. 14)
x,y,z
-x,y,-z
-x,-y,-z
x,-y,z
Space group: C 1 2/c 1 (No. 15)
x,y,z
-x,y,-z
-x,-y,-z
x,-y,z
Space group: P 2 2 2 (No. 16)
x,y,z
x,-y,-z
-x,y,-z
-x,-y,z
-x,-y,-z
-x,y,z
x,-y,z
x,y,-z
Space group: P 2 2 21 (No. 17)
x,y,z
x,-y

-x+y,y,z
-x,-x+y,z
-y,-x,z
x-y,-y,z
x,x-y,z
y,x,z
Space group: P 6/m c c (No. 192)
x,y,z
x-y,x,z
-y,x-y,z
-x,-y,z
-x+y,-x,z
y,-x+y,z
x-y,-y,-z
x,x-y,-z
y,x,-z
-x+y,y,-z
-x,-x+y,-z
-y,-x,-z
-x,-y,-z
-x+y,-x,-z
y,-x+y,-z
x,y,-z
x-y,x,-z
-y,x-y,-z
-x+y,y,z
-x,-x+y,z
-y,-x,z
x-y,-y,z
x,x-y,z
y,x,z
Space group: P 63/m c m (No. 193)
x,y,z
x-y,x,z
-y,x-y,z
-x,-y,z
-x+y,-x,z
y,-x+y,z
x-y,-y,-z
x,x-y,-z
y,x,-z
-x+y,y,-z
-x,-x+y,-z
-y,-x,-z
-x,-y,-z
-x+y,-x,-z
y,-x+y,-z
x,y,-z
x-y,x,-z
-y,x-y,-z
-x+y,y,z
-x,-x+y,z
-y,-x,z
x-y,-y,z
x,x-y,z
y,x,z
Space group: P 63/m m c (No. 194)
x,y,z
x-y,x,z
-y,x-y,z
-x,-y,z
-x+y,-x,z
y,-x+y,z
x-y,-y,-z
x,x-y,-z
y,x,-z
-x+y,y,-z
-x,-x+y,-z
-y,-x,-z
-x,-y,-z
-x+y,-x,-z
y,-x+y,-z
x,y,-z
x-y,x,-z
-y,x-y,-z
-x+y,y,z
-x,-x+y,z
-y,-x,z
x-y,-y,z
x,x-y,z
y,x,z
Space group: P 2 3 (No. 195)
x,y,z
z,x,y
y,z,x
-y,-z,x
x,-y,-z
-z,x,-y
z,-x,-y
-x,y,-z
-z,-x,y
y,-z,-x
-y,z,-x
-x,-y,z
-x,-y,-z
-z,-x,-y
-y,-z,-x
y,z,-x
-x,y,z
z,-x,y
-z,x,y
x,-y,z
z,x,-y
-y,z,x
y,-z,x
x,y,-z
Spac

In [15]:
# next: reduce #142 reflections to min set and test rules.

In [16]:
reflist

[array([0, 0, 0]),
 array([-1,  0,  0]),
 array([ 0, -1,  0]),
 array([ 0,  0, -1]),
 array([0, 0, 1]),
 array([0, 1, 0]),
 array([1, 0, 0]),
 array([-1, -1,  0]),
 array([-1,  0, -1]),
 array([-1,  0,  1]),
 array([-1,  1,  0]),
 array([ 0, -1, -1]),
 array([ 0, -1,  1]),
 array([ 0,  1, -1]),
 array([0, 1, 1]),
 array([ 1, -1,  0]),
 array([ 1,  0, -1]),
 array([1, 0, 1]),
 array([1, 1, 0]),
 array([-1, -1, -1]),
 array([-1, -1,  1]),
 array([-1,  1, -1]),
 array([-1,  1,  1]),
 array([ 1, -1, -1]),
 array([ 1, -1,  1]),
 array([ 1,  1, -1]),
 array([1, 1, 1]),
 array([-2,  0,  0]),
 array([ 0, -2,  0]),
 array([ 0,  0, -2]),
 array([0, 0, 2]),
 array([0, 2, 0]),
 array([2, 0, 0]),
 array([-2, -1,  0]),
 array([-2,  0, -1]),
 array([-2,  0,  1]),
 array([-2,  1,  0]),
 array([-1, -2,  0]),
 array([-1,  0, -2]),
 array([-1,  0,  2]),
 array([-1,  2,  0]),
 array([ 0, -2, -1]),
 array([ 0, -2,  1]),
 array([ 0, -1, -2]),
 array([ 0, -1,  2]),
 array([ 0,  1, -2]),
 array([0, 1, 2]),
 a